---
title: "Analysis"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
```

```{r df_tidy, collapse=TRUE,message=FALSE, include=FALSE}
tax_df = read_csv( "data_import_cleaning/tax.csv")
state_tax_df = read_csv("data_import_cleaning/state_tax_df.csv")

# https://abbreviations.yourdictionary.com/articles/state-abbrev.html
state_ref = 
  read.delim("./data_import_cleaning/state_abbreviation.txt", header = F) %>%
  separate(V1, into = c("state", "state_abbrv"), sep = " - ") 

# jurisdiction informatiomn
licence = 
  read_table("./data_import_cleaning/licence_jurisdiction_modified.txt") %>%
  unlist()
control = 
  read_table("./data_import_cleaning/control_jurisdiction_modified.txt") %>%
  unlist()

# tidy tax data: state with abbreviation + group
tax_df_group =  
  left_join(tax_df %>% rename(state_abbrv = state), 
            state_ref, by = "state_abbrv") %>% 
  mutate(
    group = ifelse(state %in% licence, "licenced", 
                   ifelse(state %in% control, "control", "NA"))
  ) %>% 
  relocate(state_abbrv, state, group) %>% 
  slice(-52)

state_tax_df_group = 
  left_join(state_tax_df, state_ref, by = "state") %>% 
  mutate(
    group = ifelse(state %in% licence, "licenced", 
                   ifelse(state %in% control, "control", "NA"))
  ) %>% 
  relocate(state_abbrv, state, group)
```

## Tax differences by jurisdiction group

```{r collapse=TRUE}
# tax
year = colnames(tax_df_group)[-c(1:3)]
t_test_output = NULL
for (i in 1:length(year)) {
  t_test = t.test(tax_df_group[[year[i]]]~group, data = tax_df_group) %>% broom::tidy()
  t_test_output = rbind(t_test_output, t_test)
}
t_test_output %>% 
  mutate(year = year) %>% 
  relocate(year) %>% 
  rename(
    control_est = estimate1, 
    licensed_est = estimate2, 
    control_minus_licenced = estimate) %>% 
  select(year, control_minus_licenced, p.value, conf.low, conf.high)
```


## State/local tax differences by jurisdiction group

### State
```{r}
# state_tax

state_tax_group_result = 
  state_tax_df_group %>% 
  nest(data = -year) %>% 
  mutate(
    t_test = map(.x = data, ~t.test(state_taxes ~ group, data = .x)),
    result = map(t_test, broom::tidy)
  ) %>% 
  select(year, result) %>% 
  unnest(result) %>% 
  rename(control_est = estimate1, 
         licensed_est = estimate2,
         control_minus_licensed = estimate) %>% 
  select(year, control_minus_licensed, p.value, conf.low, conf.high) %>% 
  janitor::clean_names()

#data = state_tax_df_group %>% filter(year == "2009") %>% select(state_taxes, group)
#t.test(state_taxes ~ group, data = data)

state_tax_group_result %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = year, y = control_minus_licensed)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high))
```

### Local

```{r}
# local_tax

local_tax_group_result = 
  state_tax_df_group %>% 
  rename(local_taxes = and_local_taxes) %>% 
  nest(data = -year) %>% 
  mutate(
    t_test = map(.x = data, ~t.test(local_taxes ~ group, data = .x)),
    result = map(t_test, broom::tidy)
  ) %>% 
  select(year, result) %>% 
  unnest(result) %>% 
  rename(control_est = estimate1, 
         licensed_est = estimate2,
         control_minus_licensed = estimate) %>% 
  select(year, control_minus_licensed, p.value, conf.low, conf.high) %>% 
  janitor::clean_names()

local_tax_group_result %>% 
  mutate(year = as.character(year)) %>% 
  ggplot(aes(x = year, y = control_minus_licensed)) +
  geom_point() + 
  geom_errorbar(aes(ymin = conf_low, ymax = conf_high))
```

