---
title: "tax model"
author: "Amy Pitts"
date: "11/13/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plotly)
library(flexdashboard)

library(lme4)
#library(lmerTest)
```

### get the data! 
```{r, warning=FALSE, message=FALSE}
tax_df         = read_csv( "data_import_cleaning/tax.csv")
#tax_cans_df    = read_csv("data_import_cleaning/tax_cans.csv")
#tax_barrels_df = read_csv("data_import_cleaning/tax_barrels_df.csv")
```

### Looking at just the taxes collected by state 
```{r}
tax_df %>%
  filter(state != "total") %>%
  pivot_longer(
    c(`2008`:`2019`),
    names_to = "year",
    values_to = "tax"
  ) %>%
  mutate(text_label = str_c("state: ", state)) %>% # creating text label 
  plot_ly( #using plotly to plot he tmax and tmin 
    x = ~year, y = ~tax, color = ~factor(state), text = ~text_label,
    alpha = .5, type = "scatter", mode = "lines", colors = "viridis") %>%
  layout( # adding a title 
    title = "Tax collected over the years by state")
```

```{r}
#### Mixed Effect Model 

# data 
longer_tax_df = tax_df %>%
  mutate(
    region = case_when(
      state %in% c("CT","ME","MA","NH","RI","VT","NJ","NY","PA") ~ "NorthEast",
      state %in% c("IN","IL","MI","OH","WI","IA","KS","MN","MO","NE",
             "ND","SD") ~ "MidWest",
      state %in%  c("DE","DC","FL","GA","MD","NC","SC","VA","WV","AL",
            "KY","MS","TN","AR","LA","OK","TX") ~ "South",
      state %in% c("AZ","CO","ID","NM","MT","UT","NV","WY","AK","CA",
            "HI","OR","WA") ~ "West"
    )
  ) %>%
  filter(state != "total") %>%
  pivot_longer(
    c(`2008`:`2019`),
    names_to = "year",
    values_to = "tax"
  )
  

# fitting out model 
tax_model = lmer(tax ~ as.numeric(year) + ( 1 | state), 
               data=longer_tax_df,
               REML = FALSE)


summary(tax_model)

```

```{r}
ggplot(fortify(tax_model), aes(year, tax, color=state)) +
  stat_summary(fun.data=mean_se, geom="pointrange") +
  stat_summary(aes(y=.fitted), fun.y=mean, geom="line")
```

```{r}
longer_tax_df %>%
  filter(region == "West") %>%
  ggplot(aes(x=as.numeric(year), y=tax, col = state)) +
    geom_point() +
    geom_smooth(method = lm,
                se     = FALSE,
                size   = 0.5,
                alpha  = .8)

longer_tax_df %>%
  filter(region == "MidWest") %>%
  ggplot(aes(x=as.numeric(year), y=tax, col = state)) +
    geom_point() +
    geom_smooth(method = lm,
                se     = FALSE,
                size   = 0.5,
                alpha  = .8)

longer_tax_df %>%
  filter(region == "NorthEast") %>%
  ggplot(aes(x=as.numeric(year), y=tax, col = state)) +
    geom_point() +
    geom_smooth(method = lm,
                se     = FALSE,
                size   = 0.5,
                alpha  = .8)
longer_tax_df %>%
  filter(region == "South") %>%
  ggplot(aes(x=as.numeric(year), y=tax, col = state)) +
    geom_point() +
    geom_smooth(method = lm,
                se     = FALSE,
                size   = 0.5,
                alpha  = .8)

longer_tax_df %>%
  ggplot(aes(x=as.numeric(year), y=tax, col = state)) +
    geom_point() +
    geom_smooth(method = lm,
                se     = FALSE,
                size   = 0.5,
                alpha  = .8)
```


