---
title: "Beer Tax Determined"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(tidyverse)
library(plotly)
library(flexdashboard)
# rmarkdown::render("dashboard_tax_state_map.Rmd", output_format = "flexdashboard::flex_dashboard") #knit for web
```


```{r}
tax_df = read_csv("../data_import_cleaning/tax.csv")
state_df = # arrange row order
  tibble(
    state = state.abb, # arrange row order according default state.abb
    state.name = state.name
  )

tax <- 
  left_join(state_df, tax_df, by = "state")

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  lakecolor = toRGB('white')
)

tax_2010 <- tax %>% pull(5)
tax_2011 <- tax %>% pull(6)
tax_2012 <- tax %>% pull(7)
tax_2013 <- tax %>% pull(8)
tax_2014 <- tax %>% pull(9)
tax_2015 <- tax %>% pull(10)
tax_2016 <- tax %>% pull(11)
tax_2017 <- tax %>% pull(12)
tax_2018 <- tax %>% pull(13)
tax_2019 <- tax %>% pull(14)
```
Map
=====================================  
Yearly Statistical Beer Data by State (2010 – 2019) from [Alcohol and Tobacco Tax and Trade Bureau](https://www.ttb.gov/beer/statistics)

Column
-------------------------------------
    
### Overall Trend
    
```{r trend}
tax %>%
  select(!c(3,4)) %>%
  pivot_longer(
    c(`2010`:`2019`),
    names_to = "Year",
    values_to = "Tax"
  ) %>%

  plot_ly( 
    x = ~Year, y = ~Tax, color = ~factor(state.name),
    alpha = .5, type = "scatter", mode = "lines", colors = "viridis",
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', Year,
                      '</br> Tax: ', Tax)) %>%
  layout( # adding a title 
    title = "Taxation over Years (In Barrels)")

```
   
Column {.tabset .tabset-fade}
-------------------------------------

### Year 2010
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2010, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2010,
                      '</br> Tax: ', tax_2010)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2010 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2011
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2011, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2011,
                      '</br> Tax: ', tax_2011)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2011 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2012
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2012, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2012,
                      '</br> Tax: ', tax_2012)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2012 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2013
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2013, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2013,
                      '</br> Tax: ', tax_2013)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2013 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2014
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2014, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2014,
                      '</br> Tax: ', tax_2014)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2014 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2015
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2015, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2015,
                      '</br> Tax: ', tax_2015)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2015 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2016
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2016, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2016,
                      '</br> Tax: ', tax_2016)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2016 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2017
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2017, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2017,
                      '</br> Tax: ', tax_2017)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2017 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2018
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2018, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2018,
                      '</br> Tax: ', tax_2018)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2018 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

### Year 2019
```{r}
plot_geo() %>%
  add_trace(
    z = ~tax_2019, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2019,
                      '</br> Tax: ', tax_2019)
  ) %>%
  layout(geo = g,
         title = "Taxation Choropleth of 2019 (In Barrels)") %>%
  config( fillFrame = TRUE)
```

Data
=====================================  
Yearly Statistical Beer Data by State (2010 – 2019) from [Alcohol and Tobacco Tax and Trade Bureau](https://www.ttb.gov/beer/statistics)
```{r}
knitr::kable(tax[,-c(3,4)])
# rmarkdown::render("dashboard_tax_state_map.Rmd", output_format = "flexdashboard::flex_dashboard") #knit for web
```

