---
title: "Beer Consumption"
output: 
  flexdashboard::flex_dashboard
---

```{r setup, include=FALSE}
library(tidyverse)
# devtools::install_version("plotly", version = "4.8.0", repos = "cran.us.r-project.org")  #install lower version for proper layout
library(plotly)
library(flexdashboard)
```

```{r}
state_df = read_csv("../data_import_cleaning/state_df.csv")
# View(beer)
# View(state_df)

consum_df = state_df %>%
  select(state, consumption, year) %>%
  pivot_wider(
    names_from = "year",
    values_from = "consumption"
  )
# View(consum_df)

state_info = #arrange row order
  tibble(
    state = state.name, # arrange row order according default state.abb
    state.abb = state.abb
  )

consumption <- 
  left_join(state_info, consum_df, by = "state")

g <- list(
  scope = 'usa',
  projection = list(type = 'albers usa'),
  lakecolor = toRGB('white')
)
```

Map
=====================================  
This data is gotten from [America's Beer Distributors](https://www.nbwa.org/resources/state-data). 


Column
-------------------------------------
    
### Overall Trend
    
```{r warning=FALSE, message=FALSE}
consumption %>%
  select(!c(3,9)) %>%
  pivot_longer(
    c(`2010`:`2019`),
    names_to = "year",
    values_to = "consumption"
  ) %>%

  plot_ly( 
    x = ~year, y = ~consumption, color = ~factor(state),
    alpha = .5, type = "scatter", mode = "lines", colors = "viridis",
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year:', year,
                      '</br> Consumption:', consumption)) %>%
  layout( # adding a title 
    title = "Consumption over Years ( Per Capita in Barrels)")

```

Column {.tabset .tabset-fade}
-------------------------------------
### Year 2010
```{r}
consumption_2010 <- consumption %>% pull(10)
plot_geo() %>%
  add_trace(
    z = ~consumption_2010 , span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2010,
                      '</br> Consumption: ', consumption_2010)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2010 ( Per Capita in Barrels)")
```

### Year 2011
```{r}
consumption_2011 <- consumption %>% pull(11)
plot_geo() %>%
  add_trace(
    z = ~consumption_2011 ,span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2011,
                      '</br> Consumption: ', consumption_2011)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2011 ( Per Capita in Barrels)")
```

### Year 2012
```{r}
consumption_2012 <- consumption %>% pull(12)
plot_geo() %>%
  add_trace(
    z = ~consumption_2012 , span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2012,
                      '</br> Consumption: ', consumption_2012)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2012 ( Per Capita in Barrels)")
```

### Year 2013
```{r}
consumption_2013 <- consumption %>% pull(13)
plot_geo() %>%
  add_trace(
    z = ~consumption_2013 ,span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2013,
                      '</br> Consumption: ', consumption_2013)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2013 ( Per Capita in Barrels)")
```

### Year 2014
```{r}
consumption_2014 <- consumption %>% pull(14)
plot_geo() %>%
  add_trace(
    z = ~consumption_2014, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2014,
                      '</br> Consumption: ', consumption_2014)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2014 ( Per Capita in Barrels)")
```

### Year 2015
```{r}
consumption_2015 <- consumption %>% pull(15)
plot_geo() %>%
  add_trace(
    z = ~consumption_2015, span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2015,
                      '</br> Consumption: ', consumption_2015)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2015 ( Per Capita in Barrels)")
```

### Year 2016
```{r}
consumption_2016 <- consumption %>% pull(16)
plot_geo() %>%
  add_trace(
    z = ~consumption_2016 , span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2016,
                      '</br> Consumption: ', consumption_2016)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2016 ( Per Capita in Barrels)")
```

### Year 2017
```{r}
consumption_2017 <- consumption %>% pull(17)
plot_geo() %>%
  add_trace(
    z = ~consumption_2017 , span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2017,
                      '</br> Consumption: ', consumption_2017)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2017 ( Per Capita in Barrels)")
```

### Year 2018
```{r}
consumption_2018 <- consumption %>% pull(18)
plot_geo() %>%
  add_trace(
    z = ~consumption_2018 , span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2018,
                      '</br> Consumption: ', consumption_2018)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2018 ( Per Capita in Barrels)")
```

### Year 2019
```{r}
consumption_2019 <- consumption %>% pull(19)
plot_geo() %>%
  add_trace(
    z = ~consumption_2019 , span = I(0),
    locations = state.abb, locationmode = 'USA-states',
    hoverinfo = 'text',
    text = ~paste('</br>', state.name,
                      '</br> Year: ', 2019,
                      '</br> Consumption: ', consumption_2019)
  ) %>%
  layout(geo = g,
         title = "Consumption Choropleth in 2019 ( Per Capita in Barrels)")
```

Data
=====================================  
This data is gotten from [America's Beer Distributors](https://www.nbwa.org/resources/state-data). 

```{r}
knitr::kable(consumption[,-(3:9)])
# rmarkdown::render("dashboard_comsum_statemap.Rmd", output_format = "flexdashboard::flex_dashboard") #knit for web
```